{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "homework.serviceAccountName" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "homework.fullname" . }}-metrics
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "homework.fullname" . }}-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "homework.fullname" . }}-metrics
subjects:
  - kind: ServiceAccount
    name: {{ include "homework.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
